name: 'RushJS Identify Changed Projects Helper'
author: Paul Mowat
description: 'Github action for detecting changed projects using rush change files'
runs:
  using: 'node18'
  main: 'dist/main/index.js'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  exclude-dependant-projects:
    description: 'Exclude Dependant Projects'
    required: false
    default: false
  version-policy:
    description: 'Version policy name'
    required: false
  working-directory:
    description: 'Specify the root directory for the rush configuration'
    required: false
    default: '.'
outputs:
  changed-projects: # output will be available to future steps
    description: 'List of the changed projects. Contains the packageName of each project'
